### ISSUE TITLE
Contacts not geting stubbed

### ISSUE THREAD

**Issue by UgabugaTDK** [NovaVoidHowl/CVRFury#29]
I have no idea what is is or if it's even a of physbones
just wanna make sure it's something you are aware of

![Udklip](https://github.com/user-attachments/assets/3e876062-f317-4a1f-864e-d00d6d7ac847)

**Comment by NovaVoidHowl** [comment]
Thanks for the report 

The Contacts and Receivers are the VRC equivalent of CVRs Pointers and Triggers
Currently they are not stubbed as I had not come across them in any VRCFury prefabs I have reviewed so far.

I will look into adding stubbing/auto removal for them

**Comment by NovaVoidHowl** [comment]
Stubbing and partial conversion (prefab only) added as of d504467bb3e9ae6a06778134161c98d00251877a (dev branch)
note that 'proximity' mode Receivers -> Triggers is not currently supported

**Comment by NovaVoidHowl** [comment]
Further fixes as of 8460b57e15c8b8001e1409cc8e890d8283e27a29 (dev branch) to resolve issue with partial conversion on prefabs that had more than one type of component to convert ie. Constraint and Contact Sender

**Comment by NovaVoidHowl** [comment]
as of [0.182.0-alpha](https://github.com/NovaVoidHowl/CVRFury/releases/tag/0.182.0-alpha) conversion of Contacts and Receivers is in place with the following exceptions

- no support for 'proximity' mode Receivers (omi direction distance value)
- animations for such components are not converted (though this should not be a problem as it looks like you are not allowed to animate such components in VRC, ref [3rd party extended docs](https://vrc.school/docs/Avatars/Contacts/#204b815eb3ba49c7af6c32aef243e484))

**Comment by NovaVoidHowl** [comment]
As of [#0.183.1-alpha](https://github.com/NovaVoidHowl/CVRFury/releases/tag/0.183.1-alpha) added support for  'proximity' mode Receivers (omi direction distance value)
